array_width = 42
attr_fn_like_width = 20
chain_width = 50
fn_call_width = 88
comment_width = 80
doc_comment_code_block_width = 100
inline_attribute_width = 0
max_width = 88
short_array_element_width_threshold = 10# Width threshold for an array element to be considered short
single_line_if_else_max_width = 20
single_line_let_else_max_width = 20
struct_lit_width = 18
struct_variant_width = 35
error_on_line_overflow = false
error_on_unformatted = false
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
group_imports = "StdExternalCrate"
hard_tabs = false
# tab_spaces = 2
hex_literal_case = "Upper"
show_parse_errors = true
imports_granularity = "Module"

imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
make_backup = false
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Auto"
normalize_doc_attributes = false
overflow_delimited_expr = false
print_misformatted_file_names = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.8.0"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = false
wrap_comments = false
